logging:
  level:
    root: INFO
    sql: DEBUG
    projects.realestatemanager: DEBUG
spring:
  application:
    name: real-estate-manager
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/final_project?useSSL=false&serverTimezone=UTC
    username: root
    password:
    data:
      classpath: data.sql
      initialization-mode: always
