spring:
  application:
    name: real-estate-manager

  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:real

logging:
  level:
    root: WARN
    projects.realestatemanager: DEBUG